from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes
from config import TELEGRAM_BOT_TOKEN, logger
import memory
from dispatcher import process_prompt
from research import perform_local_research
from projects import ProjectManager

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    memory.save_message(user.id, "system", "User started the bot.")
    await update.message.reply_text(
        f"Hello {user.first_name}! I am J.A.R.V.I.S., your autonomous assistant.\n\n"
        "Phase 2 Features Active:\n"
        "• 🔎 `/research <query>` - Live web search & Local GraphRAG\n"
        "• 🛠️ `/project <name>` - Autonomous Project Generator\n"
        "• ⚡ Agentic Feedback Execution Loop"
    )

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Available Commands:\n"
        "/research <topic> - Perform local machine web search & GraphRAG extraction\n"
        "/project <name> - Create a new autonomous software project\n"
        "Or simply text me any task!"
    )

async def research_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = " ".join(context.args)
    if not query:
        await update.message.reply_text("Please provide a search topic. Example: `/research latest space discoveries`")
        return
        
    await update.message.reply_text(f"🔎 Performing local machine web search & GraphRAG for: *{query}*...", parse_mode="Markdown")
    context_data = perform_local_research(query)
    
    # Truncate for Telegram message limits if needed
    formatted_msg = f"📚 **GraphRAG Context Payload:**\n\n```json\n{context_data[:3500]}\n```"
    await update.message.reply_text(formatted_msg, parse_mode="Markdown")

async def project_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    project_name = " ".join(context.args)
    if not project_name:
        await update.message.reply_text("Please provide a project name. Example: `/project my_agent`")
        return
        
    pm = ProjectManager(project_name)
    path = pm.create_project(description=f"User requested project: {project_name}")
    pm.write_file("main.py", "# Auto-generated by J.A.R.V.I.S.\n\ndef main():\n    print('Project initial entrypoint')\n\nif __name__ == '__main__':\n    main()\n")
    
    await update.message.reply_text(f"🛠️ **Project Created!**\nName: `{project_name}`\nPath: `{path}`\nInitialized `main.py` & `project.json`.", parse_mode="Markdown")

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    user_prompt = update.message.text
    
    memory.save_message(user.id, "user", user_prompt)
    logger.info(f"Received message from {user.first_name}: {user_prompt}")
    
    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action='typing')
    
    context_msgs = memory.get_recent_messages(user.id, limit=5)
    response_text = process_prompt(user_prompt, context=context_msgs)
    
    memory.save_message(user.id, "assistant", response_text)
    await update.message.reply_text(response_text, parse_mode="Markdown")

def main():
    memory.init_db()
    
    if not TELEGRAM_BOT_TOKEN:
        logger.error("Cannot start bot without TELEGRAM_BOT_TOKEN")
        return

    application = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("research", research_command))
    application.add_handler(CommandHandler("project", project_command))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    logger.info("Starting Jarvis Telegram Bot (Phase 2 with GraphRAG & Agentic Loop)...")
    application.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == '__main__':
    main()
