import os
import tempfile
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes
from config import TELEGRAM_BOT_TOKEN, logger
import memory
from dispatcher import process_prompt
from research import perform_local_research
from projects import ProjectManager
from voice import transcribe_audio_file
from computer_use import take_desktop_screenshot

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    memory.save_message(user.id, "system", "User started the bot.")
    await update.message.reply_text(
        f"Hello {user.first_name}! I am J.A.R.V.I.S., your autonomous assistant.\n\n"
        "Phase 1-4 Complete Capabilities:\n"
        "• 🎙️ Voice Notes -> CPU Faster-Whisper STT\n"
        "• 🖥️ `/screenshot` -> Take & view desktop screenshot\n"
        "• 🔎 `/research <query>` -> Local WebSearch & GraphRAG\n"
        "• 🛠️ `/project <name>` -> Autonomous Project Generator\n"
        "• ⚡ Agentic Feedback Loop Sandbox"
    )

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Available Commands:\n"
        "/research <topic> - Local machine web search & GraphRAG extraction\n"
        "/project <name> - Create a new autonomous software project\n"
        "/screenshot - Capture current desktop screen\n"
        "Send voice notes or text prompts directly to J.A.R.V.I.S.!"
    )

async def screenshot_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("📸 Capturing desktop screenshot...")
    path = take_desktop_screenshot()
    if path and os.path.exists(path):
        with open(path, 'rb') as photo:
            await update.message.reply_photo(photo=photo, caption="🖥️ Current Desktop Screenshot")
    else:
        await update.message.reply_text("❌ Failed to capture screenshot.")

async def research_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = " ".join(context.args)
    if not query:
        await update.message.reply_text("Please provide a search topic. Example: `/research latest space discoveries`")
        return
        
    await update.message.reply_text(f"🔎 Performing local machine web search & GraphRAG for: *{query}*...", parse_mode="Markdown")
    context_data = perform_local_research(query)
    formatted_msg = f"📚 **GraphRAG Context Payload:**\n\n```json\n{context_data[:3500]}\n```"
    await update.message.reply_text(formatted_msg, parse_mode="Markdown")

async def project_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    project_name = " ".join(context.args)
    if not project_name:
        await update.message.reply_text("Please provide a project name. Example: `/project my_agent`")
        return
        
    pm = ProjectManager(project_name)
    path = pm.create_project(description=f"User requested project: {project_name}")
    pm.write_file("main.py", "# Auto-generated by J.A.R.V.I.S.\n\ndef main():\n    print('Project initial entrypoint')\n\nif __name__ == '__main__':\n    main()\n")
    
    await update.message.reply_text(f"🛠️ **Project Created!**\nName: `{project_name}`\nPath: `{path}`\nInitialized `main.py` & `project.json`.", parse_mode="Markdown")

async def handle_voice_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    voice = update.message.voice
    
    await update.message.reply_text("🎙️ Processing voice note with CPU Faster-Whisper...")
    
    # Download telegram .ogg voice file
    file = await context.bot.get_file(voice.file_id)
    temp_dir = tempfile.gettempdir()
    ogg_path = os.path.join(temp_dir, f"voice_{voice.file_id}.ogg")
    await file.download_to_drive(ogg_path)
    
    # Transcribe via voice module
    transcript = transcribe_audio_file(ogg_path)
    
    if os.path.exists(ogg_path):
        os.remove(ogg_path)
        
    await update.message.reply_text(f"🗣️ **Transcript:** \"{transcript}\"\n\nProcessing intent...", parse_mode="Markdown")
    
    # Save transcript to memory and pass to Dispatcher
    memory.save_message(user.id, "user", f"[Voice Note]: {transcript}")
    response_text = process_prompt(transcript, context=memory.get_recent_messages(user.id, limit=5))
    memory.save_message(user.id, "assistant", response_text)
    
    await update.message.reply_text(response_text, parse_mode="Markdown")

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    user_prompt = update.message.text
    
    memory.save_message(user.id, "user", user_prompt)
    logger.info(f"Received message from {user.first_name}: {user_prompt}")
    
    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action='typing')
    
    context_msgs = memory.get_recent_messages(user.id, limit=5)
    response_text = process_prompt(user_prompt, context=context_msgs)
    
    memory.save_message(user.id, "assistant", response_text)
    await update.message.reply_text(response_text, parse_mode="Markdown")

def main():
    memory.init_db()
    
    if not TELEGRAM_BOT_TOKEN:
        logger.error("Cannot start bot without TELEGRAM_BOT_TOKEN")
        return

    application = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("research", research_command))
    application.add_handler(CommandHandler("project", project_command))
    application.add_handler(CommandHandler("screenshot", screenshot_command))
    application.add_handler(MessageHandler(filters.VOICE, handle_voice_message))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    logger.info("Starting Jarvis Telegram Bot (Phase 1-4 Complete Stack)...")
    application.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == '__main__':
    main()
